### ISSUE TITLE
GrayGetSwitchCount does not work on HW3

### ISSUE THREAD

**Issue by been-jamming** [debrouxl/gcc4ti#14]
On HW3, `GrayGetSwitchCount` seems to not work, or simply never return a different value. Functions such as `GrayWaitNSwitches` and `GrayDBufToggleSync` seem to freeze when run on tiemu as well as on actual hardware. I am using `tigcc version 1.3.4 built for TIGCC/*nix version 0.96 Beta 11 r1`.

**Comment by debrouxl** [comment]
From which branch and which HEAD commit did you make that build, and on which host type (Linux, MacOS X, *BSD), processor architecture and version ?
Also, which program did you use ? I'd expect a simple grayscale demo to show the issue anyway, but still, it's best to provide your (reduced) testcase :)

__switch_cnt / __gray_switch_cnt is incremented from both the HW1 and HW2 interrupt handlers (both before and after my more or less recent optimizations on the experimental branch, which isn't the default one), and these variables are declared volatile as they should be, so expressions using these shouldn't be turned into infinite loops, which is one of the ways to yield apparent freezes.

**Comment by been-jamming** [comment]
I made a mistake and didn't realize that it was because I was running these grayscale routines inside of an interrupt 5 handler. Everything works fine outside of the interrupt handler!

**Comment by debrouxl** [comment]
Indeed, the grayscale routines use interrupt level 1 :)
I'll let you close this issue.

**Comment by kkofler** [comment]
> I am using `tigcc version 1.3.4 built for TIGCC/*nix version 0.96 Beta 11 r1`.

No, you are not. You are using something that **claims** to be `tigcc version 1.3.4 built for TIGCC/*nix version 0.96 Beta 11 r1`. There is no "TIGCC/*nix version 0.96 Beta 11 r1" (the latest release is 0.96 Beta 8 r1), and the executable is the GCC4TI CLI that incorrectly claims to be "tigcc". At the very least, the "built for TIGCC/*nix" part could be changed, it is only a string and could easily say the truth, i.e., "built for GCC4TI", instead.
